version: '3.4'

services:
  demoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8443;http://+:8447
    expose:
      - "8443"
    ports:
      - "8447:8447"
      - "7239:7239"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  #telegramclientserver:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #  ports:
  #    - "80"
  #    - "443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
